Repository pysal/splot, pull requests merged in 2019-06, with the labels that each got.

#69 set up dual travis tests for pysal dependencies (pip and github)
  .travis.yml
  requirements_dev.txt
Labels: maintenance

#70 Add aspect_equal argument to Moran functionality
  notebooks/esda_morans_viz.ipynb
  splot/_viz_esda_mpl.py
  splot/tests/test_viz_esda_mpl.py
Labels: enhancement, maintenance, roadmap

#73 [ENH] select colour by presence of value in list in `mask_local_auto`
  splot/_viz_utils.py
Labels: bug
